<!dock type html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="/signUpPage" method="post">
    <input name="email" type="text" placeholder="Email">
    <input name="password" type="password" placeholder="Password">
    <input type="submit" value="SIGN UP">
</form>
</body>
</html>