<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
</head>

<body>
<p><a class="nav_link" href="/signUp" data-scroll="#">Registration</a></p>
<p><a class="nav_link" href="/signIn" data-scroll="#">Authorization</a></p>
<p><a class="nav_link" href="/users" data-scroll="#">Users List</a></p>
<p><a class="nav_link" href="/profile" data-scroll="#">My profile</a></p>
<p><a class="nav_link" href="/addPost" data-scroll="#">+ Post</a></p>
</body>

</html>